BEGIN TRANSACTION;
CREATE TABLE `weather` (
	`Id`	INTEGER NOT NULL,
	`city`	TEXT
);
INSERT INTO `weather` VALUES (1,NULL);
INSERT INTO `weather` VALUES (2,NULL);
INSERT INTO `weather` VALUES (3,NULL);
INSERT INTO `weather` VALUES (4,NULL);
INSERT INTO `weather` VALUES (5,NULL);
COMMIT;
